version: 1
applications:
  - appRoot: frontend
    phases:
      preBuild:
        commands:
          - cd frontend
          - npm install
      build:
        commands:
          - npm run build
    artifacts:
      baseDirectory: frontend/build
      files:
        - '**/*'
    cache:
      paths:
        - frontend/node_modules/**/*
